# Generated by Django 5.2.9 on 2026-06-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('harvest_reminder', 'Harvest Reminder'), ('buyer_alert', 'Buyer Alert'), ('system', 'System Notification'), ('chat_message', 'Chat Message')], max_length=20),
        ),
    ]
