# Generated by Django 5.2.9 on 2026-05-31 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_cropreservation_order_waitlist'),
        ('orders', '0002_orderitem_status_alter_order_order_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='crop_growth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.cropgrowth'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='is_prebooking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='crop_growth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crops.cropgrowth'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_prebooking',
            field=models.BooleanField(default=False),
        ),
    ]
