# Generated by Django 5.2.9 on 2026-05-31 12:47

from django.db import migrations

def update_status(apps, schema_editor):
    OrderItem = apps.get_model('orders', 'OrderItem')
    OrderItem.objects.filter(status='confirmed').update(status='processing')
    
    Order = apps.get_model('orders', 'Order')
    # Order model never had 'confirmed', but just in case
    Order.objects.filter(status='confirmed').update(status='processing')

class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitem_status_orderstatushistory'),
    ]

    operations = [
        migrations.RunPython(update_status, reverse_code=migrations.RunPython.noop),
    ]
