# Generated by Django 5.2.9 on 2026-06-22 05:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0003_rename_updated_at_cropgrowth_last_updated_and_more'),
        ('orders', '0005_update_order_status_confirmed_to_processing'),
        ('products', '0004_product_products_pr_is_avai_c23034_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer'], name='orders_orde_buyer_i_90aa29_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='orders_orde_status_c6dd84_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order'], name='orders_orde_order_i_5d347b_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['farmer'], name='orders_orde_farmer__894dc6_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['status'], name='orders_orde_status_863d47_idx'),
        ),
    ]
