# Generated by Django 5.2.9 on 2026-05-29 15:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sow_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('current_stage', models.CharField(choices=[('sown', 'Sown'), ('growing', 'Growing'), ('ready_for_harvest', 'Ready for Harvest'), ('harvested', 'Harvested')], default='sown', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='crop_tracking', to='products.product')),
            ],
            options={
                'ordering': ['-expected_harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='CropStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sown', 'Sown'), ('growing', 'Growing'), ('ready_for_harvest', 'Ready for Harvest'), ('harvested', 'Harvested')], max_length=20)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('crop_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='products.croptracking')),
            ],
            options={
                'verbose_name_plural': 'Crop Status Histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='BuyerCropInterest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True)),
                ('notified', models.BooleanField(default=False)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_interests', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_interests', to='products.product')),
            ],
            options={
                'unique_together': {('product', 'buyer')},
            },
        ),
        migrations.CreateModel(
            name='HarvestReminderLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('7_days', '7 Days Before'), ('3_days', '3 Days Before'), ('0_days', 'Harvest Day')], max_length=10)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('crop_tracking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders_sent', to='products.croptracking')),
            ],
            options={
                'unique_together': {('crop_tracking', 'reminder_type')},
            },
        ),
    ]
