# Generated by Django 5.2.9 on 2026-05-31 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_croptracking_cropstatushistory_buyercropinterest_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='harvestreminderlog',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='cropstatushistory',
            name='crop_tracking',
        ),
        migrations.RemoveField(
            model_name='croptracking',
            name='product',
        ),
        migrations.RemoveField(
            model_name='harvestreminderlog',
            name='crop_tracking',
        ),
        migrations.DeleteModel(
            name='BuyerCropInterest',
        ),
        migrations.DeleteModel(
            name='CropStatusHistory',
        ),
        migrations.DeleteModel(
            name='CropTracking',
        ),
        migrations.DeleteModel(
            name='HarvestReminderLog',
        ),
    ]
