# Generated by Django 5.2.9 on 2026-05-30 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_farmers', models.IntegerField(default=0)),
                ('total_buyers', models.IntegerField(default=0)),
                ('active_users', models.IntegerField(default=0)),
                ('total_products', models.IntegerField(default=0)),
                ('total_orders', models.IntegerField(default=0)),
                ('total_revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='BusinessInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('insight_type', models.CharField(choices=[('demand', 'Demand'), ('supply', 'Supply'), ('revenue', 'Revenue'), ('user', 'User Growth'), ('operations', 'Operations')], max_length=20)),
                ('message', models.TextField()),
                ('is_actionable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
