# Generated by Django 5.2.9 on 2026-05-31 05:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0003_remove_cropstatushistory_crop_tracking_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CropGrowth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sowing_date', models.DateField()),
                ('expected_harvest_date', models.DateField()),
                ('actual_harvest_date', models.DateField(blank=True, null=True)),
                ('expected_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('available_quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('crop_stage', models.CharField(choices=[('PLANNED', 'Planned'), ('SOWN', 'Sown'), ('GERMINATION', 'Germination'), ('VEGETATIVE', 'Vegetative'), ('FLOWERING', 'Flowering'), ('FRUITING', 'Fruiting'), ('READY_FOR_HARVEST', 'Ready for Harvest'), ('HARVESTED', 'Harvested'), ('SOLD_OUT', 'Sold Out')], default='PLANNED', max_length=20)),
                ('organic', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('farmer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_growths', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crop_growths', to='products.product')),
            ],
            options={
                'ordering': ['-expected_harvest_date'],
            },
        ),
        migrations.CreateModel(
            name='CropReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_reserved', models.DecimalField(decimal_places=2, max_digits=10)),
                ('reservation_status', models.CharField(choices=[('PENDING', 'Pending'), ('CONFIRMED', 'Confirmed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('reserved_at', models.DateTimeField(auto_now_add=True)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='crop_reservations', to=settings.AUTH_USER_MODEL)),
                ('crop_growth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='crops.cropgrowth')),
            ],
            options={
                'ordering': ['-reserved_at'],
            },
        ),
        migrations.CreateModel(
            name='CropStageHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_stage', models.CharField(blank=True, choices=[('PLANNED', 'Planned'), ('SOWN', 'Sown'), ('GERMINATION', 'Germination'), ('VEGETATIVE', 'Vegetative'), ('FLOWERING', 'Flowering'), ('FRUITING', 'Fruiting'), ('READY_FOR_HARVEST', 'Ready for Harvest'), ('HARVESTED', 'Harvested'), ('SOLD_OUT', 'Sold Out')], max_length=20, null=True)),
                ('current_stage', models.CharField(choices=[('PLANNED', 'Planned'), ('SOWN', 'Sown'), ('GERMINATION', 'Germination'), ('VEGETATIVE', 'Vegetative'), ('FLOWERING', 'Flowering'), ('FRUITING', 'Fruiting'), ('READY_FOR_HARVEST', 'Ready for Harvest'), ('HARVESTED', 'Harvested'), ('SOLD_OUT', 'Sold Out')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('crop_growth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stage_history', to='crops.cropgrowth')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Crop Stage Histories',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CropFollower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_crops', to=settings.AUTH_USER_MODEL)),
                ('crop_growth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='crops.cropgrowth')),
            ],
            options={
                'unique_together': {('buyer', 'crop_growth')},
            },
        ),
    ]
