# Generated by Django 5.2.9 on 2026-06-06 12:26

from django.db import migrations, models

def map_crop_stages(apps, schema_editor):
    CropGrowth = apps.get_model('crops', 'CropGrowth')
    CropStageHistory = apps.get_model('crops', 'CropStageHistory')

    stage_mapping = {
        'GERMINATION': 'PLANTED',
        'PLANNED': 'PLANTED',
        'SOWN': 'PLANTED',
        'VEGETATIVE': 'GROWING',
        'FLOWERING': 'GROWING',
        'FRUITING': 'NEAR_HARVEST',
        'MATURITY': 'NEAR_HARVEST',
        'READY_FOR_HARVEST': 'NEAR_HARVEST',
        'HARVESTED': 'HARVESTED',
        'SOLD_OUT': 'HARVESTED',
    }

    # Map CropGrowth.stage
    for crop in CropGrowth.objects.all():
        if crop.stage in stage_mapping:
            crop.stage = stage_mapping[crop.stage]
            crop.save(update_fields=['stage'])

    # Map CropStageHistory.current_stage and previous_stage
    for history in CropStageHistory.objects.all():
        updated = False
        if history.current_stage in stage_mapping:
            history.current_stage = stage_mapping[history.current_stage]
            updated = True
        if history.previous_stage in stage_mapping:
            history.previous_stage = stage_mapping[history.previous_stage]
            updated = True
        if updated:
            history.save(update_fields=['current_stage', 'previous_stage'])

def reverse_map_crop_stages(apps, schema_editor):
    pass # Cannot reverse accurately

class Migration(migrations.Migration):

    dependencies = [
        ('crops', '0002_cropreservation_order_waitlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cropgrowth',
            old_name='updated_at',
            new_name='last_updated',
        ),
        migrations.RenameField(
            model_name='cropgrowth',
            old_name='crop_stage',
            new_name='stage',
        ),
        migrations.RunPython(map_crop_stages, reverse_map_crop_stages),
        migrations.AlterField(
            model_name='cropgrowth',
            name='stage',
            field=models.CharField(choices=[('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('NEAR_HARVEST', 'Near Harvest'), ('HARVESTED', 'Harvested')], default='PLANTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='cropstagehistory',
            name='current_stage',
            field=models.CharField(choices=[('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('NEAR_HARVEST', 'Near Harvest'), ('HARVESTED', 'Harvested')], max_length=20),
        ),
        migrations.AlterField(
            model_name='cropstagehistory',
            name='previous_stage',
            field=models.CharField(blank=True, choices=[('PLANTED', 'Planted'), ('GROWING', 'Growing'), ('NEAR_HARVEST', 'Near Harvest'), ('HARVESTED', 'Harvested')], max_length=20, null=True),
        ),
    ]
